### ISSUE TITLE
As an admin user, I can login to the app, and if I'm listed as one of the admins in whatever configuration file applies, the app will show that I am an admin.   And I will have access to a special admin menu (which for the time being might have nothing on it.)

### ISSUE THREAD

**Issue by Ulramok** [ucsb-cs48-s20/project-idea-reviewer-nextjs#2]
- [x] There is a clear documented way for a user to add themself as an initial admin user
- [x] When logging in as an admin user, the admin menu can be accessed
- [x] When logging in as user not in the admin table, the admin menu cannot be accessed
- [x] The page that the admin menu links to, when present, should not be accessible to non admin menus that might know or be able to guess the URL

**Comment by pconrad** [comment]
I'm reopening this issue and dragging it back into the TODO column because until there is documentation in the README as to how to add initial admin users, this one isn't done.
