### ISSUE TITLE
As an instructor, I can upload a CSV file of students in egrades format, and it will populate a students table with first name, last name, email and perm number.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs48-s20/project-idea-reviewer-nextjs#5]
- [x] Every row in CSV file gets added to students table with correct name, perm, email.
- [x] Old entries in student table are retained 
- [x] Nice to have: Entries with matching perms are not duplicated (we didn't do this in the Spring Boot MVP because we were short on time, but this would definitely be preferable) 
- [x] Nice to have: any emails that get uploaded in `@umail.ucsb.edu` format are converted to `@ucsb.edu` format (not sure if this was in the Spring Boot version, but it's nice to have this be consistent.    Egrades file are currently a mish-mosh of old and new formats, but logins through Google OAuth will only be the new format, I think)

**Comment by pconrad** [comment]
https://github.com/project-anacapa/egrades-faker

**Comment by pconrad** [comment]
You may like to comment here with the branch name for this issue, e.g. tkCSVUpload or something like that.

**Comment by Ulramok** [comment]
The branch name is tkCSVUpload
