### ISSUE TITLE
Number of ratings and avg project rating appears on project index page.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs48-s20/project-idea-reviewer-nextjs#7]
- [ ] number of ratings appears on the project index page 
- [ ] number of ratings shown is accurate
- [ ] avg rating appears on the project index page 
- [ ] avg rating shown is accurate

User Story: As an instructor, I can see the number of ratings and the average rating on the project index page, and sort by those, so that I can (a) see whether we have enough ratings to end the exercise, (b) sort the projects and see the highest rated one.

Note that strictly speaking only (a) has to be in the app for this to be MVP.  But since this is probably implemented with bootstrap-table or a React equivalent, it's probably reasonable to go for both.    (b) isn't strictly needed because in the MVP life cycle, that sort happens after we copy/paste the results into a google sheet.

**Comment by Ulramok** [comment]
Redundant issue
